/-
Authors: Formal Frontier Agents
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Data.Finsupp.Weight
public import Mathlib.RingTheory.MvPolynomial.Ideal
public import Mathlib.RingTheory.Spectrum.Prime.Topology
public import ToricIdeals.MonoidAlgebra.FiberNormalization

/-!
# The toric ideal of a rational normal curve

For `n ≥ 1`, this file identifies the ideal of `2 × 2` minors of the
Hankel matrix with rows `x₀, …, xₙ₋₁` and `x₁, …, xₙ` with the
kernel of `xᵢ ↦ a^(n-i) b^i`, over an arbitrary commutative ring.

The easy inclusion follows by evaluating each generator. For the reverse
inclusion, a Hankel relation moves an occupied separated pair inward, preserves
the target exponent, and strictly decreases natural-number energy. Repeating
this move yields adjacent support; degree and weight determine the terminal
exponent. Positive `n` lets the target exponents recover source degree, so
terminal representatives can be selected by target fiber. The generic
coefficientwise normalization theorem then handles arbitrary coefficients.
These representatives use classical choice, not a computable reduction API.

The degree-zero exception, degree-one equality, quotient-to-*range* equivalence,
and domain-dependent consequences are stated separately below.
-/

open MvPolynomial

namespace ToricIdeals.RationalNormalCurve

noncomputable section

@[expose] public section

universe u

variable (k : Type u) [CommRing k]

/-- The polynomial ring in `x₀, …, xₙ`. -/
abbrev Source (n : ℕ) := MvPolynomial (Fin (n + 1)) k

/-- The polynomial ring in the two target variables `a` and `b`. -/
abbrev Target := MvPolynomial (Fin 2) k

/-- The exponent pair `(n-i, i)` of the image of `xᵢ`. -/
def coordinateExponent (n : ℕ) (i : Fin (n + 1)) : Fin 2 →₀ ℕ :=
  Finsupp.single (0 : Fin 2) (n - i.val) +
    Finsupp.single (1 : Fin 2) i.val

/-- The additive exponent map induced by `xᵢ ↦ a^(n-i) b^i`. -/
def rncExponent (n : ℕ) : (Fin (n + 1) →₀ ℕ) →+ (Fin 2 →₀ ℕ) :=
  Finsupp.weight (coordinateExponent n)

/-- The monomial parametrization `xᵢ ↦ a^(n-i) b^i`. -/
def rncMap (n : ℕ) : Source k n →+* Target k :=
  AddMonoidAlgebra.mapDomainRingHom k (rncExponent n)

/-- Ordered pairs of distinct columns of the `2 × n` Hankel matrix. -/
abbrev MinorIndex (n : ℕ) := {p : Fin n × Fin n // p.1 < p.2}

/-- The minor `x_i*x_(j+1) - x_(i+1)*x_j` for columns `i < j`. -/
def hankelMinor (n : ℕ) (p : MinorIndex n) : Source k n :=
  X p.1.1.castSucc * X p.1.2.succ - X p.1.1.succ * X p.1.2.castSucc

/-- The ideal generated by all `2 × 2` minors of the Hankel matrix. -/
def hankelIdeal (n : ℕ) : Ideal (Source k n) :=
  Ideal.span (Set.range (hankelMinor k n))

/-- A source variable has exactly its designated target exponent. -/
@[simp] theorem rncExponent_single (n : ℕ) (i : Fin (n + 1)) :
    rncExponent n (Finsupp.single i 1) = coordinateExponent n i := by
  rw [rncExponent, Finsupp.weight_single]
  exact one_nsmul (coordinateExponent n i)

/-- The parametrization takes `X i` to the monomial of exponent `(n-i,i)`. -/
@[simp] theorem rncMap_X (n : ℕ) (i : Fin (n + 1)) :
    rncMap k n (X i) = monomial (coordinateExponent n i) 1 := by
  rw [rncMap, AddMonoidAlgebra.mapDomainRingHom_apply]
  change AddMonoidAlgebra.mapDomain (rncExponent n)
      (AddMonoidAlgebra.single (Finsupp.single i 1) 1) = _
  rw [AddMonoidAlgebra.mapDomain_single, rncExponent_single]
  rfl

/-- The two products in an ordered Hankel minor have equal target exponents. -/
theorem minor_exponents_agree (n : ℕ) (p : MinorIndex n) :
    coordinateExponent n p.1.1.castSucc + coordinateExponent n p.1.2.succ =
      coordinateExponent n p.1.1.succ + coordinateExponent n p.1.2.castSucc := by
  ext q
  fin_cases q <;> simp [coordinateExponent] <;> omega

/-- Each displayed minor belongs to the ideal it generates. -/
theorem minor_mem (n : ℕ) (p : MinorIndex n) :
    hankelMinor k n p ∈ hankelIdeal k n := by
  apply Ideal.subset_span
  exact Set.mem_range_self p

/-- Every Hankel minor vanishes under the rational-normal-curve map, for all
`n` and all commutative coefficient rings. -/
theorem hankelIdeal_le_ker (n : ℕ) :
    hankelIdeal k n ≤ RingHom.ker (rncMap k n) := by
  apply Ideal.span_le.2
  rintro _ ⟨p, rfl⟩
  change rncMap k n (hankelMinor k n p) = 0
  simp only [hankelMinor, map_sub, map_mul, rncMap_X]
  rw [MvPolynomial.monomial_mul_monomial, MvPolynomial.monomial_mul_monomial,
    minor_exponents_agree n p]
  simp

/-- At degree zero the Hankel matrix has no ordered pair of columns. -/
theorem hankelIdeal_zero : hankelIdeal k 0 = ⊥ := by
  rw [hankelIdeal, Ideal.span_eq_bot]
  rintro _ ⟨p, rfl⟩
  exact Fin.elim0 p.1.1

/-- At degree one its single column supplies no `2 × 2` minor. -/
theorem hankelIdeal_one : hankelIdeal k 1 = ⊥ := by
  rw [hankelIdeal, Ideal.span_eq_bot]
  rintro _ ⟨p, rfl⟩
  have : p.1.1 = p.1.2 := Subsingleton.elim _ _
  exact ((ne_of_lt p.2) this).elim

/-- Degree zero is genuinely exceptional over every nontrivial coefficient
ring: the sole variable maps to `1`, while there are no minors. -/
theorem hankelIdeal_zero_lt_ker [Nontrivial k] :
    hankelIdeal k 0 < RingHom.ker (rncMap k 0) := by
  apply lt_of_le_of_ne (hankelIdeal_le_ker k 0)
  intro heq
  let f : Source k 0 := X 0 - C 1
  have hfker : f ∈ RingHom.ker (rncMap k 0) := by
    change rncMap k 0 (X 0 - C 1) = 0
    simp [rncMap_X, coordinateExponent]
  have hfne : f ≠ 0 := by
    intro hf
    have hs : (Finsupp.single (0 : Fin 1) 1 : Fin 1 →₀ ℕ) ≠ 0 := by simp
    have hcoeff := congrArg
      (fun g : Source k 0 ↦ g.coeff (Finsupp.single 0 1)) hf
    change (X (0 : Fin 1) - C 1 : Source k 0).coeff
      (Finsupp.single 0 1) = 0 at hcoeff
    rw [MvPolynomial.coeff_sub, MvPolynomial.coeff_X_same,
      MvPolynomial.coeff_C_of_ne_zero hs] at hcoeff
    simp at hcoeff
  have hfideal : f ∈ hankelIdeal k 0 := by
    rw [heq]
    exact hfker
  rw [hankelIdeal_zero] at hfideal
  exact hfne hfideal

/-- At degree one the exponent map on the two source variables is the identity. -/
theorem rncExponent_one (d : Fin (1 + 1) →₀ ℕ) : rncExponent 1 d = d := by
  ext i
  fin_cases i <;>
    simp [rncExponent, Finsupp.weight_eq_sum, coordinateExponent, Fin.sum_univ_two]

/-- The degree-one monomial parametrization is injective. -/
theorem rncMap_one_injective : Function.Injective (rncMap k 1) := by
  apply AddMonoidAlgebra.mapDomain_injective
  intro d e h
  simpa only [rncExponent_one] using h

/-- Degree one is valid but trivial: there are no minors and the
parametrization is injective. -/
theorem hankelIdeal_one_eq_ker :
    hankelIdeal k 1 = RingHom.ker (rncMap k 1) := by
  rw [hankelIdeal_one]
  exact (RingHom.injective_iff_ker_eq_bot (rncMap k 1)).mp
    (rncMap_one_injective k) |>.symm

/-- Total number of source variables in a source monomial. -/
abbrev sourceDegree (n : ℕ) : (Fin (n + 1) →₀ ℕ) →+ ℕ :=
  Finsupp.degree

/-- Weighted index sum `∑ i, i*d_i` of a source monomial. -/
def sourceWeight (n : ℕ) : (Fin (n + 1) →₀ ℕ) →+ ℕ :=
  Finsupp.weight (fun i : Fin (n + 1) ↦ i.val)

/-- Convex termination measure `∑ i, i²*d_i`. -/
def sourceEnergy (n : ℕ) : (Fin (n + 1) →₀ ℕ) →+ ℕ :=
  Finsupp.weight (fun i : Fin (n + 1) ↦ i.val ^ 2)

/-- The two separated endpoint variables occurring in a Hankel minor. -/
def outerExponent (n : ℕ) (p : MinorIndex n) : Fin (n + 1) →₀ ℕ :=
  Finsupp.single p.1.1.castSucc 1 + Finsupp.single p.1.2.succ 1

/-- The two variables one step closer together in the same Hankel minor. -/
def innerExponent (n : ℕ) (p : MinorIndex n) : Fin (n + 1) →₀ ℕ :=
  Finsupp.single p.1.1.succ 1 + Finsupp.single p.1.2.castSucc 1

/-- Replace one occupied separated pair by the corresponding closer pair. -/
def reduceExponent (n : ℕ) (d : Fin (n + 1) →₀ ℕ) (p : MinorIndex n) :
    Fin (n + 1) →₀ ℕ :=
  d - outerExponent n p + innerExponent n p

/-- Multiplication of coefficient-one source monomials adds their exponents. -/
theorem monomial_add_one (n : ℕ) (d e : Fin (n + 1) →₀ ℕ) :
    (monomial (d + e) 1 : Source k n) = monomial d 1 * monomial e 1 := by
  rw [MvPolynomial.monomial_mul_monomial, one_mul]

/-- The outer-minus-inner monomial relation is the corresponding Hankel minor. -/
theorem monomial_outer_sub_inner (n : ℕ) (p : MinorIndex n) :
    (monomial (outerExponent n p) 1 - monomial (innerExponent n p) 1 :
      Source k n) = hankelMinor k n p := by
  simp only [outerExponent, innerExponent, monomial_add_one]
  simp [hankelMinor, X]

/-- A single inward move preserves the target exponent on its replaced pair. -/
theorem rncExponent_outer_eq_inner (n : ℕ) (p : MinorIndex n) :
    rncExponent n (outerExponent n p) = rncExponent n (innerExponent n p) := by
  simp only [outerExponent, innerExponent, map_add, rncExponent_single]
  exact minor_exponents_agree n p

/-- The closer pair has strictly smaller squared-index energy. -/
theorem inner_energy_lt_outer_energy (n : ℕ) (p : MinorIndex n) :
    sourceEnergy n (innerExponent n p) < sourceEnergy n (outerExponent n p) := by
  simp only [sourceEnergy, innerExponent, outerExponent, map_add,
    Finsupp.weight_single, one_nsmul]
  simp only [Fin.val_succ, Fin.val_castSucc, pow_two]
  simp only [Nat.add_mul, Nat.mul_add, one_mul, mul_one]
  have := p.2
  omega

/-- An applicable inward move preserves the full monomial's target exponent. -/
theorem reduceExponent_preserves_rncExponent (n : ℕ)
    (d : Fin (n + 1) →₀ ℕ) (p : MinorIndex n) (h : outerExponent n p ≤ d) :
    rncExponent n (reduceExponent n d p) = rncExponent n d := by
  have hcancel : d - outerExponent n p + outerExponent n p = d :=
    tsub_add_cancel_of_le h
  calc
    rncExponent n (reduceExponent n d p) =
        rncExponent n (d - outerExponent n p) +
          rncExponent n (innerExponent n p) := by rw [reduceExponent, map_add]
    _ = rncExponent n (d - outerExponent n p) +
          rncExponent n (outerExponent n p) := by
        rw [rncExponent_outer_eq_inner n p]
    _ = rncExponent n d := by rw [← map_add, hcancel]

/-- An applicable inward move strictly decreases natural-number energy. -/
theorem reduceExponent_energy_lt (n : ℕ)
    (d : Fin (n + 1) →₀ ℕ) (p : MinorIndex n) (h : outerExponent n p ≤ d) :
    sourceEnergy n (reduceExponent n d p) < sourceEnergy n d := by
  have hcancel : d - outerExponent n p + outerExponent n p = d :=
    tsub_add_cancel_of_le h
  calc
    sourceEnergy n (reduceExponent n d p) =
        sourceEnergy n (d - outerExponent n p) +
          sourceEnergy n (innerExponent n p) := by rw [reduceExponent, map_add]
    _ < sourceEnergy n (d - outerExponent n p) +
          sourceEnergy n (outerExponent n p) :=
        Nat.add_lt_add_left (inner_energy_lt_outer_energy n p) _
    _ = sourceEnergy n d := by rw [← map_add, hcancel]

/-- The monomial change in an applicable inward move is a multiple of a minor,
so its difference belongs to `hankelIdeal`. -/
theorem monomial_sub_reduceExponent_mem (n : ℕ)
    (d : Fin (n + 1) →₀ ℕ) (p : MinorIndex n) (h : outerExponent n p ≤ d) :
    (monomial d 1 - monomial (reduceExponent n d p) 1 : Source k n) ∈
      hankelIdeal k n := by
  let q := d - outerExponent n p
  have hcancel : q + outerExponent n p = d := tsub_add_cancel_of_le h
  have hreduce : reduceExponent n d p = q + innerExponent n p := rfl
  have hpoly :
      (monomial d 1 - monomial (reduceExponent n d p) 1 : Source k n) =
        monomial q 1 * hankelMinor k n p := by
    rw [hreduce, ← hcancel, monomial_add_one, monomial_add_one, ← mul_sub,
      monomial_outer_sub_inner]
  rw [hpoly]
  exact Ideal.mul_mem_left _ _ (minor_mem k n p)

/-- A terminal exponent has no occupied pair separated by at least two indices;
equivalently no `outerExponent` fits inside it. -/
def Normal (n : ℕ) (d : Fin (n + 1) →₀ ℕ) : Prop :=
  ∀ p : MinorIndex n, ¬ outerExponent n p ≤ d

/-- Two occupied positions in a terminal exponent differ by at most one. -/
theorem Normal.index_le_add_one {n : ℕ} {d : Fin (n + 1) →₀ ℕ}
    (hd : Normal n d) {i j : Fin (n + 1)} (hi : d i ≠ 0) (hj : d j ≠ 0) :
    i.val ≤ j.val + 1 := by
  by_contra hle
  have hsep : j.val + 1 < i.val := by omega
  let a : Fin n := ⟨j.val, by omega⟩
  let b : Fin n := ⟨i.val - 1, by omega⟩
  have hab : a < b := by
    change j.val < i.val - 1
    omega
  let p : MinorIndex n := ⟨(a, b), hab⟩
  have ha : p.1.1.castSucc = j := by
    apply Fin.ext
    rfl
  have hb : p.1.2.succ = i := by
    apply Fin.ext
    simp only [p, b, Fin.val_succ]
    omega
  apply hd p
  intro z
  rw [outerExponent, ha, hb]
  simp only [Finsupp.add_apply, Finsupp.single_apply]
  by_cases hzj : z = j
  · subst z
    have hij : i ≠ j := by
      intro h
      have := congrArg Fin.val h
      omega
    simpa [hij] using Nat.one_le_iff_ne_zero.mpr hj
  · by_cases hzi : z = i
    · subst z
      have hji : j ≠ i := by
        intro h
        have := congrArg Fin.val h
        omega
      simpa [hzj, hji] using Nat.one_le_iff_ne_zero.mpr hi
    · have hjz : j ≠ z := Ne.symm hzj
      have hiz : i ≠ z := Ne.symm hzi
      simp [hjz, hiz]

/-- Relative to an occupied leftmost position, a terminal exponent is supported
at that position and possibly its successor. -/
theorem Normal.mem_support_eq_or_val_eq_add_one {n : ℕ}
    {d : Fin (n + 1) →₀ ℕ} (hd : Normal n d) {q i : Fin (n + 1)}
    (hq : d q ≠ 0) (hmin : q ≤ i) (hi : i ∈ d.support) :
    i = q ∨ i.val = q.val + 1 := by
  have hine : d i ≠ 0 := Finsupp.mem_support_iff.mp hi
  have hclose := hd.index_le_add_one hine hq
  by_cases heq : i = q
  · exact Or.inl heq
  · right
    have hval : q.val < i.val := by
      have := Fin.le_iff_val_le_val.mp hmin
      have hneval : i.val ≠ q.val := by
        intro h
        exact heq (Fin.ext h)
      omega
    omega

/-- Degree and weight of a terminal exponent whose leftmost occupied position
has a successor. -/
theorem Normal.degree_weight_eq_min_add_succ {n : ℕ}
    {d : Fin (n + 1) →₀ ℕ} (hd : Normal n d) {q : Fin (n + 1)}
    (hq : d q ≠ 0) (hmin : ∀ i ∈ d.support, q ≤ i) (hq_lt : q.val < n) :
    let q1 : Fin (n + 1) := ⟨q.val + 1, by omega⟩
    sourceDegree n d = d q + d q1 ∧
      sourceWeight n d = q.val * d q + q1.val * d q1 := by
  let q1 : Fin (n + 1) := ⟨q.val + 1, by omega⟩
  have hq1 : q1 ≠ q := by
    intro h
    have := congrArg Fin.val h
    simp only [q1] at this
    omega
  have hsupp : d.support ⊆ {q, q1} := by
    intro i hi
    obtain hiq | hival := hd.mem_support_eq_or_val_eq_add_one hq (hmin i hi) hi
    · simp [hiq]
    · have hiq1 : i = q1 := by
        apply Fin.ext
        simpa only [q1] using hival
      simp [hiq1]
  constructor
  · change d.sum (fun _ c ↦ c) = d q + d q1
    rw [Finsupp.sum_of_support_subset d hsupp]
    all_goals simp [Ne.symm hq1]
  · rw [sourceWeight, Finsupp.weight_apply,
      Finsupp.sum_of_support_subset d hsupp]
    all_goals simp [q1, Ne.symm hq1, Nat.add_mul, Nat.mul_comm]

/-- Explicit two-term expansion of a terminal exponent from its occupied
leftmost position. -/
theorem Normal.eq_single_add_single_succ {n : ℕ}
    {d : Fin (n + 1) →₀ ℕ} (hd : Normal n d) {q : Fin (n + 1)}
    (hq : d q ≠ 0) (hmin : ∀ i ∈ d.support, q ≤ i) (hq_lt : q.val < n) :
    let q1 : Fin (n + 1) := ⟨q.val + 1, by omega⟩
    d = Finsupp.single q (d q) + Finsupp.single q1 (d q1) := by
  let q1 : Fin (n + 1) := ⟨q.val + 1, by omega⟩
  have hq1 : q1 ≠ q := by
    intro h
    have := congrArg Fin.val h
    simp only [q1] at this
    omega
  have hsupp : d.support ⊆ {q, q1} := by
    intro i hi
    obtain hiq | hival := hd.mem_support_eq_or_val_eq_add_one hq (hmin i hi) hi
    · simp [hiq]
    · have hiq1 : i = q1 := by
        apply Fin.ext
        simpa only [q1] using hival
      simp [hiq1]
  calc
    d = d.sum Finsupp.single := (Finsupp.sum_single d).symm
    _ = ∑ i ∈ {q, q1}, Finsupp.single i (d i) := by
      rw [Finsupp.sum_of_support_subset d hsupp]
      simp
    _ = Finsupp.single q (d q) + Finsupp.single q1 (d q1) := by
      simp [Ne.symm hq1]

/-- A terminal exponent whose leftmost occupied position is the last position
is a single basis exponent. -/
theorem Normal.eq_single_of_min_eq_last {n : ℕ}
    {d : Fin (n + 1) →₀ ℕ} (_hd : Normal n d) {q : Fin (n + 1)}
    (_hq : d q ≠ 0) (hmin : ∀ i ∈ d.support, q ≤ i) (hq_last : q.val = n) :
    d = Finsupp.single q (d q) := by
  apply Finsupp.support_subset_singleton.mp
  intro i hi
  have hqi := Fin.le_iff_val_le_val.mp (hmin i hi)
  have hin := Nat.le_of_lt_succ i.isLt
  have : i = q := by
    apply Fin.ext
    omega
  simp [this]

/-- The left endpoint of a nonzero terminal exponent is the quotient of its
weight by its degree. -/
theorem Normal.min_val_eq_weight_div_degree {n : ℕ}
    {d : Fin (n + 1) →₀ ℕ} (hd : Normal n d)
    (hdegree : 0 < sourceDegree n d) :
    let hs : d.support.Nonempty := Finsupp.support_nonempty_iff.mpr
      ((Finsupp.degree_eq_zero_iff d).not.mp (Nat.ne_of_gt hdegree))
    (d.support.min' hs).val = sourceWeight n d / sourceDegree n d := by
  have hdne : d ≠ 0 :=
    (Finsupp.degree_eq_zero_iff d).not.mp (Nat.ne_of_gt hdegree)
  have hs : d.support.Nonempty := Finsupp.support_nonempty_iff.mpr hdne
  let q : Fin (n + 1) := d.support.min' hs
  have hqmem : q ∈ d.support := Finset.min'_mem d.support hs
  have hq : d q ≠ 0 := Finsupp.mem_support_iff.mp hqmem
  have hmin : ∀ i ∈ d.support, q ≤ i := by
    intro i hi
    exact Finset.min'_le d.support i hi
  change q.val = sourceWeight n d / sourceDegree n d
  by_cases hq_last : q.val = n
  · have heq := hd.eq_single_of_min_eq_last hq hmin hq_last
    rw [heq]
    simp only [sourceDegree, Finsupp.degree_single]
    rw [sourceWeight, Finsupp.weight_single]
    change q.val = d q * q.val / d q
    rw [Nat.mul_comm, Nat.mul_div_left _ (Nat.zero_lt_of_ne_zero hq)]
  · have hq_lt : q.val < n := by
      have hq_le : q.val ≤ n := Nat.le_of_lt_succ q.isLt
      omega
    let q1 : Fin (n + 1) := ⟨q.val + 1, by omega⟩
    obtain ⟨hdeg, hweight⟩ :=
      hd.degree_weight_eq_min_add_succ hq hmin hq_lt
    have hdeg' : sourceDegree n d = d q + d q1 := by
      simpa only [q1] using hdeg
    have hweight' :
        sourceWeight n d = q.val * d q + (q.val + 1) * d q1 := by
      simpa only [q1] using hweight
    have hqpos : 0 < d q := Nat.zero_lt_of_ne_zero hq
    have hdiv := (Nat.div_mod_unique hdegree).2
      (show d q1 + sourceDegree n d * q.val = sourceWeight n d ∧
          d q1 < sourceDegree n d by
        constructor
        · rw [hdeg', hweight']
          ring
        · rw [hdeg']
          omega)
    exact hdiv.1.symm

/-- Terminal exponents are determined by their total degree and weighted index
sum.  This is the adjacent-support uniqueness step behind the toric-kernel
calculation. -/
theorem Normal.eq_of_degree_weight_eq {n : ℕ}
    {d e : Fin (n + 1) →₀ ℕ} (hd : Normal n d) (he : Normal n e)
    (hdegree : sourceDegree n d = sourceDegree n e)
    (hweight : sourceWeight n d = sourceWeight n e) : d = e := by
  by_cases hd0 : sourceDegree n d = 0
  · have he0 : sourceDegree n e = 0 := hdegree ▸ hd0
    exact (Finsupp.degree_eq_zero_iff d).mp hd0 |>.trans
      ((Finsupp.degree_eq_zero_iff e).mp he0).symm
  · have hdpos : 0 < sourceDegree n d := Nat.zero_lt_of_ne_zero hd0
    have hepos : 0 < sourceDegree n e := by omega
    have hdne : d ≠ 0 :=
      (Finsupp.degree_eq_zero_iff d).not.mp hd0
    have hene : e ≠ 0 :=
      (Finsupp.degree_eq_zero_iff e).not.mp (Nat.ne_of_gt hepos)
    have hsd : d.support.Nonempty := Finsupp.support_nonempty_iff.mpr hdne
    have hse : e.support.Nonempty := Finsupp.support_nonempty_iff.mpr hene
    let qd : Fin (n + 1) := d.support.min' hsd
    let qe : Fin (n + 1) := e.support.min' hse
    have hqdmem : qd ∈ d.support := Finset.min'_mem d.support hsd
    have hqemem : qe ∈ e.support := Finset.min'_mem e.support hse
    have hqd : d qd ≠ 0 := Finsupp.mem_support_iff.mp hqdmem
    have hqe : e qe ≠ 0 := Finsupp.mem_support_iff.mp hqemem
    have hmind : ∀ i ∈ d.support, qd ≤ i := by
      intro i hi
      exact Finset.min'_le d.support i hi
    have hmine : ∀ i ∈ e.support, qe ≤ i := by
      intro i hi
      exact Finset.min'_le e.support i hi
    have hqdval := hd.min_val_eq_weight_div_degree hdpos
    have hqeval := he.min_val_eq_weight_div_degree hepos
    change qd.val = sourceWeight n d / sourceDegree n d at hqdval
    change qe.val = sourceWeight n e / sourceDegree n e at hqeval
    have hqval : qd.val = qe.val := by
      rw [hqdval, hqeval, hdegree, hweight]
    have hq : qd = qe := Fin.ext hqval
    have hqe' : e qd ≠ 0 := by
      rw [hq]
      exact hqe
    have hmine' : ∀ i ∈ e.support, qd ≤ i := by
      intro i hi
      rw [hq]
      exact hmine i hi
    by_cases hlast : qd.val = n
    · have hdeq := hd.eq_single_of_min_eq_last hqd hmind hlast
      have heeq := he.eq_single_of_min_eq_last hqe' hmine' hlast
      have hcoeff : d qd = e qd := by
        rw [hdeq, heeq] at hdegree
        simpa using hdegree
      rw [hdeq, heeq, hcoeff]
    · have hq_lt : qd.val < n := by
        have hq_le : qd.val ≤ n := Nat.le_of_lt_succ qd.isLt
        omega
      let qd1 : Fin (n + 1) := ⟨qd.val + 1, by omega⟩
      let qe1 : Fin (n + 1) := ⟨qd.val + 1, by omega⟩
      have hdeq := hd.eq_single_add_single_succ hqd hmind hq_lt
      have heeq := he.eq_single_add_single_succ hqe' hmine' hq_lt
      have hdform := hd.degree_weight_eq_min_add_succ hqd hmind hq_lt
      have heform := he.degree_weight_eq_min_add_succ hqe' hmine' hq_lt
      have hdd : sourceDegree n d = d qd + d qd1 := by
        simpa only [qd1] using hdform.1
      have hed : sourceDegree n e = e qd + e qe1 := by
        simpa only [qe1] using heform.1
      have hdw :
          sourceWeight n d = qd.val * sourceDegree n d + d qd1 := by
        have := hdform.2
        rw [hdd, this]
        ring
      have hew :
          sourceWeight n e = qd.val * sourceDegree n e + e qe1 := by
        have := heform.2
        rw [hed, this]
        ring
      have hsucc : d qd1 = e qe1 := by
        apply Nat.add_left_cancel
        calc
          qd.val * sourceDegree n d + d qd1 = sourceWeight n d := hdw.symm
          _ = sourceWeight n e := hweight
          _ = qd.val * sourceDegree n e + e qe1 := hew
          _ = qd.val * sourceDegree n d + e qe1 := by rw [hdegree]
      have hleft : d qd = e qd := by omega
      have hsuccIndex : qd1 = qe1 := by
        apply Fin.ext
        simp only [qd1, qe1]
      have hsucc' : d qe1 = e qe1 := by
        simpa only [hsuccIndex] using hsucc
      rw [show d = Finsupp.single qd (d qd) +
          Finsupp.single qd1 (d qd1) by simpa only [qd1] using hdeq,
        show e = Finsupp.single qd (e qd) +
          Finsupp.single qe1 (e qe1) by simpa only [qe1] using heeq,
        hleft, hsuccIndex, hsucc']

/-- Convex-energy reduction terminates at a terminal monomial with the same
target exponent and a coefficient-one monomial congruent modulo the Hankel ideal.
Well-founded induction on `sourceEnergy` uses the strict decrease of each move. -/
theorem exists_normal (n : ℕ) (d : Fin (n + 1) →₀ ℕ) :
    ∃ e : Fin (n + 1) →₀ ℕ,
      Normal n e ∧ rncExponent n e = rncExponent n d ∧
        (monomial d 1 - monomial e 1 : Source k n) ∈ hankelIdeal k n := by
  induction henergy : sourceEnergy n d using Nat.strong_induction_on generalizing d with
  | h m ih =>
      by_cases hnormal : Normal n d
      · exact ⟨d, hnormal, rfl, by simp⟩
      · simp only [Normal, not_forall, Classical.not_not] at hnormal
        obtain ⟨p, hp⟩ := hnormal
        let e := reduceExponent n d p
        have hlt : sourceEnergy n e < sourceEnergy n d :=
          reduceExponent_energy_lt n d p hp
        obtain ⟨q, hqnormal, hqexp, hqmem⟩ :=
          ih (sourceEnergy n e) (by omega) e rfl
        refine ⟨q, hqnormal,
          hqexp.trans (reduceExponent_preserves_rncExponent n d p hp), ?_⟩
        have hstep := monomial_sub_reduceExponent_mem k n d p hp
        have hsum :
            (monomial d 1 - monomial q 1 : Source k n) =
              (monomial d 1 - monomial e 1) +
                (monomial e 1 - monomial q 1) := by ring
        rw [hsum]
        exact (hankelIdeal k n).add_mem hstep hqmem

/-- The second target exponent is the source weighted-index sum. -/
theorem rncExponent_second (n : ℕ) (d : Fin (n + 1) →₀ ℕ) :
    rncExponent n d 1 = sourceWeight n d := by
  classical
  simp [rncExponent, sourceWeight, Finsupp.weight_eq_sum, coordinateExponent]

/-- The sum of both target exponents is `n` times the source degree.
Recovering the degree from this identity requires positive `n`. -/
theorem rncExponent_total (n : ℕ) (d : Fin (n + 1) →₀ ℕ) :
    rncExponent n d 0 + rncExponent n d 1 = n * sourceDegree n d := by
  induction d using Finsupp.induction with
  | zero => simp
  | single_add i c d hi hc ih =>
      simp only [map_add, Finsupp.degree_single]
      rw [rncExponent, Finsupp.weight_single]
      change (c • coordinateExponent n i) 0 + rncExponent n d 0 +
          ((c • coordinateExponent n i) 1 + rncExponent n d 1) =
        n * (c + sourceDegree n d)
      have hcoordinate :
          (c • coordinateExponent n i) 0 +
              (c • coordinateExponent n i) 1 = n * c := by
        have hi_le : i.val ≤ n := Nat.le_of_lt_succ i.isLt
        simp [coordinateExponent]
        rw [← Nat.mul_add, Nat.sub_add_cancel hi_le, Nat.mul_comm]
      rw [Nat.mul_add, ← ih]
      omega

/-- The rational-normal-curve exponent map is injective on terminal exponents
when `1 ≤ n`: the target pair recovers degree and weight, which determine the
terminal exponent. It is not asserted injective on every source exponent. -/
theorem rncExponent_injective_on_normal (n : ℕ) (hn : 1 ≤ n)
    {d e : Fin (n + 1) →₀ ℕ} (hd : Normal n d) (he : Normal n e)
    (hexponent : rncExponent n d = rncExponent n e) : d = e := by
  apply hd.eq_of_degree_weight_eq he
  · apply Nat.mul_left_cancel (by omega : 0 < n)
    calc
      n * sourceDegree n d =
          rncExponent n d 0 + rncExponent n d 1 :=
        (rncExponent_total n d).symm
      _ = rncExponent n e 0 + rncExponent n e 1 := by rw [hexponent]
      _ = n * sourceDegree n e := rncExponent_total n e
  · rw [← rncExponent_second n d, ← rncExponent_second n e, hexponent]

/-- A classically selected terminal exponent congruent to `d` modulo the
Hankel ideal. The selection depends on `k` and is noncomputable. -/
def normalSourceExponent (n : ℕ) (d : Fin (n + 1) →₀ ℕ) :
    Fin (n + 1) →₀ ℕ :=
  (exists_normal k n d).choose

/-- The chosen source representative is terminal. -/
theorem normalSourceExponent_normal (n : ℕ) (d : Fin (n + 1) →₀ ℕ) :
    Normal n (normalSourceExponent k n d) :=
  (exists_normal k n d).choose_spec.1

/-- The chosen source representative preserves the target exponent. -/
theorem normalSourceExponent_rncExponent (n : ℕ)
    (d : Fin (n + 1) →₀ ℕ) :
    rncExponent n (normalSourceExponent k n d) = rncExponent n d :=
  (exists_normal k n d).choose_spec.2.1

/-- The coefficient-one source monomial and its selected terminal representative
are congruent modulo the Hankel ideal. -/
theorem monomial_sub_normalSourceExponent_mem (n : ℕ)
    (d : Fin (n + 1) →₀ ℕ) :
    (monomial d 1 - monomial (normalSourceExponent k n d) 1 : Source k n) ∈
      hankelIdeal k n :=
  (exists_normal k n d).choose_spec.2.2

/-- Equal target exponents select the same terminal representative for `1 ≤ n`,
using injectivity only among terminal exponents. -/
theorem normalSourceExponent_eq_of_rncExponent_eq (n : ℕ) (hn : 1 ≤ n)
    {d e : Fin (n + 1) →₀ ℕ} (h : rncExponent n d = rncExponent n e) :
    normalSourceExponent k n d = normalSourceExponent k n e := by
  apply rncExponent_injective_on_normal n hn
      (normalSourceExponent_normal k n d) (normalSourceExponent_normal k n e)
  rw [normalSourceExponent_rncExponent, normalSourceExponent_rncExponent, h]

/-- A classical, noncomputable terminal representative selected by a target
exponent, also parameterized by the coefficient ring `k`. By definition values
outside the image of `rncExponent` are zero; no additive section is asserted. -/
def fiberNormalExponent (k : Type u) [CommRing k] (n : ℕ) (t : Fin 2 →₀ ℕ) :
    Fin (n + 1) →₀ ℕ := by
  classical
  exact if h : ∃ d, rncExponent n d = t then
      normalSourceExponent k n (Classical.choose h)
    else 0

/-- On the image of `rncExponent`, the fiber selection equals the chosen
terminal normal form for the source exponent when `1 ≤ n`. -/
theorem fiberNormalExponent_image (n : ℕ) (hn : 1 ≤ n)
    (d : Fin (n + 1) →₀ ℕ) :
    fiberNormalExponent k n (rncExponent n d) = normalSourceExponent k n d := by
  rw [fiberNormalExponent]
  split
  next h =>
    apply normalSourceExponent_eq_of_rncExponent_eq k n hn
    exact Classical.choose_spec h
  next h => exact (h ⟨d, rfl⟩).elim

/-- Reverse inclusion in the kernel calculation, obtained by normalizing each
coefficient along its target-exponent fiber. The coefficient-one congruence is
scaled by `C r` for every `r : k` and passed to the generic fiber theorem. -/
theorem ker_le_hankelIdeal (n : ℕ) (hn : 1 ≤ n) :
    RingHom.ker (rncMap k n) ≤ hankelIdeal k n := by
  intro f hf
  apply AddMonoidAlgebra.mem_ideal_of_mapDomain_eq_zero
      (hankelIdeal k n) (rncExponent n) (fiberNormalExponent k n)
  · intro d r
    change (monomial d r -
      monomial (fiberNormalExponent k n (rncExponent n d)) r : Source k n) ∈
        hankelIdeal k n
    rw [fiberNormalExponent_image k n hn]
    have hone := monomial_sub_normalSourceExponent_mem k n d
    have hscale :
        (monomial d r - monomial (normalSourceExponent k n d) r : Source k n) =
          C r * (monomial d 1 - monomial (normalSourceExponent k n d) 1) := by
      rw [mul_sub, MvPolynomial.C_mul_monomial,
        MvPolynomial.C_mul_monomial]
      simp
    rw [hscale]
    exact Ideal.mul_mem_left _ _ hone
  · exact hf

/-- For every positive `n`, the `2 × 2` Hankel minors generate exactly the
kernel of the rational-normal-curve monomial parametrization, over an arbitrary
commutative ring. -/
theorem hankelIdeal_eq_ker (n : ℕ) (hn : 1 ≤ n) :
    hankelIdeal k n = RingHom.ker (rncMap k n) :=
  le_antisymm (hankelIdeal_le_ker k n) (ker_le_hankelIdeal k n hn)

/-- The quotient by the Hankel ideal is the *image subring* of the monomial map,
not necessarily the entire two-variable target. Dependent transport in the
definition does not promise `rfl`/`simp` evaluation on arbitrary quotient
representatives; use ring-homomorphism laws such as `map_one` when appropriate. -/
def quotientEquivRange (n : ℕ) (hn : 1 ≤ n) :
    (Source k n ⧸ hankelIdeal k n) ≃+* (rncMap k n).range := by
  rw [hankelIdeal_eq_ker k n hn]
  exact RingHom.quotientKerEquivRange (rncMap k n)

/-- Over a domain, the Hankel ideal is prime. -/
theorem hankelIdeal_isPrime [IsDomain k] (n : ℕ) (hn : 1 ≤ n) :
    (hankelIdeal k n).IsPrime := by
  rw [hankelIdeal_eq_ker k n hn]
  exact RingHom.ker_isPrime (rncMap k n)

/-- Over a domain, the rational-normal-curve coordinate ring is a domain. -/
theorem quotient_isDomain [IsDomain k] (n : ℕ) (hn : 1 ≤ n) :
    IsDomain (Source k n ⧸ hankelIdeal k n) := by
  rw [Ideal.Quotient.isDomain_iff_prime]
  exact hankelIdeal_isPrime k n hn

/-- The prime spectrum of the rational-normal-curve coordinate ring is
irreducible over a domain. -/
theorem spectrum_irreducible [IsDomain k] (n : ℕ) (hn : 1 ≤ n) :
    IrreducibleSpace (PrimeSpectrum (Source k n ⧸ hankelIdeal k n)) := by
  let _ := quotient_isDomain k n hn
  infer_instance

end

end

end ToricIdeals.RationalNormalCurve
